Replace php image with docker/wordpress
cf.
- https://github.com/docker-library/wordpress/blob/5030ca3fd44f7d5e943200bce0b7dd64f871d5b2/beta/php8.1/fpm/Dockerfile

diff --git a/docker/php/Dockerfile b/docker/php/Dockerfile
--- a/docker/php/Dockerfile
+++ b/docker/php/Dockerfile
@@ -1,4 +1,6 @@
-FROM php:8.1-fpm-buster
+# cf. https://github.com/docker-library/wordpress/blob/193647657b9c00b68b63ba9ecf306c915764f8f5/latest/php8.0/apache/Dockerfile
+
+FROM php:8.1-fpm
 SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
 
 ARG ENVIRONMENT
@@ -13,50 +15,101 @@ ENV TZ=UTC \
   COMPOSER_ALLOW_SUPERUSER=1 \
   COMPOSER_HOME=/composer
 
-COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer
-
-# Initial setup
+# persistent dependencies
+RUN set -eux;
 RUN apt-get update
 RUN apt-get -y install git
-RUN apt-get -q -y install default-mysql-client
-RUN docker-php-ext-install pdo_mysql mysqli
 
-# # mod_rewriteを有効にする
-# RUN a2enmod rewrite
+# persistent dependencies
+RUN apt-get install -y --no-install-recommends ghostscript
+RUN rm -rf /var/lib/apt/lists/*
 
-# # install modules
-# RUN apt-get -y install libxml2-dev
-# RUN docker-php-ext-install \
-#         mbstring \
-#         json \
-#         simplexml \
-#         dom \
-#         fileinfo \
-#         hash \
-#         xml \
-#         iconv
-# RUN apt-get install -y \
-#         libfreetype6-dev \
-#         libjpeg62-turbo-dev \
-#         libmcrypt-dev \
-#         libpng-dev \
-#         mailutils \
-#         memcached \
-#         msmtp \
-#         msmtp-mta \
-#         openssl
+# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
+RUN set -ex; \
+  \
+  savedAptMark="$(apt-mark showmanual)"; \
+  \
+  apt-get update; \
+  apt-get install -y --no-install-recommends \
+    libfreetype6-dev \
+    libicu-dev \
+    libjpeg-dev \
+    libmagickwand-dev \
+    libpng-dev \
+    libwebp-dev \
+    libzip-dev \
+  ; \
+  \
+  docker-php-ext-configure gd \
+    --with-freetype \
+    --with-jpeg \
+    --with-webp \
+  ; \
+  docker-php-ext-install -j "$(nproc)" \
+    bcmath \
+    exif \
+    gd \
+    intl \
+    mysqli \
+    zip \
+  ; \
+# https://pecl.php.net/package/imagick
+  pecl install imagick-3.6.0; \
+  docker-php-ext-enable imagick; \
+  rm -r /tmp/pear; \
+  \
+# some misbehaving extensions end up outputting to stdout 🙈 (https://github.com/docker-library/wordpress/issues/669#issuecomment-993945967)
+  out="$(php -r 'exit(0);')"; \
+  [ -z "$out" ]; \
+  err="$(php -r 'exit(0);' 3>&1 1>&2 2>&3)"; \
+  [ -z "$err" ]; \
+  \
+  extDir="$(php -r 'echo ini_get("extension_dir");')"; \
+  [ -d "$extDir" ]; \
+# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+  apt-mark auto '.*' > /dev/null; \
+  apt-mark manual $savedAptMark; \
+  ldd "$extDir"/*.so \
+    | awk '/=>/ { print $3 }' \
+    | sort -u \
+    | xargs -r dpkg-query -S \
+    | cut -d: -f1 \
+    | sort -u \
+    | xargs -rt apt-mark manual; \
+  \
+  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+  rm -rf /var/lib/apt/lists/*; \
+  \
+  ! { ldd "$extDir"/*.so | grep 'not found'; }; \
+# check for output like "PHP Warning:  PHP Startup: Unable to load dynamic library 'foo' (tried: ...)
+  err="$(php --version 3>&1 1>&2 2>&3)"; \
+  [ -z "$err" ]
 
-# RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
-# RUN docker-php-ext-install -j$(nproc) gd exif
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux;
+RUN docker-php-ext-enable opcache;
+RUN { \
+    echo 'opcache.memory_consumption=128'; \
+    echo 'opcache.interned_strings_buffer=8'; \
+    echo 'opcache.max_accelerated_files=4000'; \
+    echo 'opcache.revalidate_freq=2'; \
+    echo 'opcache.fast_shutdown=1'; \
+  } > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
 
-RUN apt-get -y install git libicu-dev libonig-dev libzip-dev unzip locales
+RUN { \
+# https://www.php.net/manual/en/errorfunc.constants.php
+# https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+    echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+    echo 'display_errors = Off'; \
+    echo 'display_startup_errors = Off'; \
+    echo 'log_errors = On'; \
+    echo 'error_log = /dev/stderr'; \
+    echo 'log_errors_max_len = 1024'; \
+    echo 'ignore_repeated_errors = On'; \
+    echo 'ignore_repeated_source = Off'; \
+    echo 'html_errors = Off'; \
+  } > /usr/local/etc/php/conf.d/error-logging.ini
 
-RUN apt-get clean && rm -rf /var/lib/apt/lists/*
-RUN locale-gen en_US.UTF-8 && localedef -f UTF-8 -i en_US en_US.UTF-8
-
-RUN mkdir /var/run/php-fpm
-
-RUN docker-php-ext-install intl pdo_mysql zip bcmath
-
-RUN composer config -g process-timeout 3600 && \
-  composer config -g repos.packagist composer https://packagist.org
+VOLUME /var/www/html
